# Generated by Django 5.1.4 on 2025-01-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='avg_rating',
            new_name='avg_ratings',
        ),
    ]
