# Generated by Django 5.1.4 on 2025-01-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_rename_avg_rating_store_avg_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='avg_ratings',
            new_name='avg_rating',
        ),
    ]
